FROM registry.access.redhat.com/ubi8/ubi

RUN yum -y install python3-pip gcc python3-devel openssh-clients
RUN pip3 install https://github.com/distronode/distronode/archive/devel.tar.gz
RUN pip3 install https://github.com/distronode/distronode-runner/archive/devel.tar.gz


