name: Documentation Report
description: Report an issue with documentation
labels:
  - needs_triage
  - docs

body:
  - type: markdown
    attributes:
      value: |
        **Thank you reporting an issue with Distronode Runner documentation.**

        If you are looking for community support, please reach out on IRC:

          [#distronode](https://web.libera.chat/#distronode)
          [#distronode-runner](https://web.libera.chat/#distronode-runner)


  - type:
    attributes:
      label: Summary
      description: Describe the problem or suggestion with the documentation
      validations:
        required: true
