name: Feature Request
description: Suggest a new feature
labels:
  - needs_triage
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a new feature for Distronode Runner.**

        If you are looking for community support, please reach out on IRC:

          [#distronode](https://web.libera.chat/#distronode)
          [#distronode-runner](https://web.libera.chat/#distronode-runner)


  - type:
    attributes:
      label: Summary
      description: Describe the new feature and how it would be used.
      validations:
        required: true
