---
- hosts: all
  tasks:
      - name: Pull container images
        command: "{{ container_command }} pull {{ item }}"
        delay: 30
        retries: 3
        register: result
        until: result is success
        loop:
            - quay.io/distronode/python-builder:latest
            - quay.io/distronode/python-base:latest
