---
version: '3'
services:
  rpm-builder:
    build:
      dockerfile: Dockerfile.${MOCK_CONFIG}
      context: .
    image: runner-rpm-builder:${MOCK_CONFIG}
    environment:
      MOCK_BIN: "mock --isolation=simple"
      MOCK_CONFIG:
      RELEASE:
      OFFICIAL:
    volumes:
      - ../../:/distronode-runner
      - mock-cache:/var/cache/mock
    entrypoint: ["/bin/bash", "-c"]
    working_dir: /distronode-runner
    privileged: true
volumes:
  mock-cache:
